spring:
 datasource:
  username: "root"
  password: "root"
  url: "jdbc:mariadb://localhost:3306/fornecedor"
 jpa:
  hibernate:
   ddl-auto: "update"
  properties:
   dialect: "org.hibernate.dialect.MariaDB103Dialect"
   
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.datasource.url=jdbc:mariadb://localhost:3306/fornecedor
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB103Dialect
